name: Go package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Build
        run: |
          export GOPATH=$(pwd)
          cd src/monkey
          go build -v ./...

      - name: Test
        run: |
          export GOPATH=$(pwd)
          cd src/monkey
          go test -v ./...
